### ISSUE TITLE
Automatically create link on sub-pages

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/pyramid-ogcapi#2]
With the OpenAPI configuration of all the existing routes, then we can provide a function that automatically creates the OGC API link to the sub-pages.

This should also create a link on self page.

see also: https://docs.ogc.org/is/19-072/19-072.html#_11b9b4f7-42fc-413a-b63a-e7fb060b5e4b

Replace https://github.com/camptocamp/pyramid-ogcapi/blob/master/acceptance_tests/pyramid_ogcapi_test_app/ogcapi/__init__.py#L39-L44
With a function like:
`def self_link(request, title: str):`
Will use `current_route_url`

Replace https://github.com/camptocamp/pyramid-ogcapi/blob/master/acceptance_tests/pyramid_ogcapi_test_app/ogcapi/__init__.py#L57-L62 (and the next one)
With a function like:
`def link(request, apiname:str, path: str, rel: str):`
Will use the open api schema available in `request.settings[apiname]`

**Comment by vuilleumierc** [comment]
Closed by https://github.com/camptocamp/pyramid-ogcapi/pull/21
